### ISSUE TITLE
Error in OAuth Server: invalid_scope

### ISSUE THREAD

**Issue by Thimoteus** [PandaWhisperer/meteor-accounts-reddit#4]
I'm using `accounts-ui` and set up my client id and secret with it. When I go to log in, it says "log in completed" but on the server I get the following:

```
W20141205-21:40:25.605(1) (oauth_server.js:78) Unable to parse state from OAuth query: µw{²GÛEñÕ
W20141205-21:40:25.624(1) (oauth_server.js:78) Unable to parse state from OAuth query: µw{²GÛEñÕ
W20141205-21:40:25.635(1) (oauth_server.js:398) Error in OAuth Server: invalid_scope
```

The [reddit OAuth2 documentation](https://github.com/reddit/reddit/wiki/OAuth2) says "Ensure that the `scope` parameter is a comma-separated list of valid scopes" but I'm not sure what to do with this information.

**Comment by mscherer82** [comment]
I got the same problem. The user agent can be added in the reddit-oauth.js in the getIdentity() Method. After adding I got another error: 

W20150107-16:26:21.435(1) (oauth_server.js:78) Unable to parse state from OAuth query: {À+é4çQè±Ä
W20150107-16:26:21.437(1) (oauth_server.js:398) Error in OAuth Server: Unexpected OAuth service reddit
I20150107-16:26:21.581(1)? Exception while invoking method 'login' Error: Unexpected OAuth service reddit
I20150107-16:26:21.581(1)?     at middleware (packages/oauth/oauth_server.js:165:1)
I20150107-16:26:21.581(1)?     at packages/oauth/oauth_server.js:146:1

This is fired in the oauth.js of the OAuth package in the middleware function. 

    var service = registeredServices[serviceName];                           
                                                                                               
    // Skip everything if there's no service set by the oauth middleware    
    if (!service)                                                                         
      throw new Error("Unexpected OAuth service " + serviceName);

I don't know why the service isn't stored in the registeredServices array, because it seems that the OAuth.registerService function will be called correctly.

**Comment by PandaWhisperer** [comment]
Hey guys. Just updated this package for use with Meteor 1.2. Not sure if any of you are still using it, but if you could test it out, would love to hear your feedback. Thanks!

**Comment by MrOpposite** [comment]
I fixed this issue in https://github.com/PandaWhisperer/meteor-reddit-oauth/pull/5 by adding a default scope 'read'.

(A whopping 6 character pull request! but it's my first, you gotta start somewhere.)

**Comment by janzheng** [comment]
for just using Reddit to login, seems like using 'identity' would be the most private scope (for just Oauth login)

**Comment by SimplyLinn** [comment]
Ah, you're right. I should have read the reddit documentation better 😞 

Ah well I might add another PR at some point.
